version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: DriveLiveDie_db
    restart: "no"
    volumes:
      - DriveLiveDie_Data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - dld-network

  pgadming:
    image: dpage/pgadmin4
    container_name: DriveLiveDie_pgadmin
    restart: "no"
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - dld-network

  backend:
    image: arkadiuszjuszczykue/dld-be:latest
    container_name: DriveLiveDie_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - 8008:80
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - dld-network

  test:
    build:
      context: ./backend
    command: pytest
    volumes:
      - .:/code
    depends_on:
      - db

  frontend:
    image: arkadiuszjuszczykue/dld-fe:latest
    container_name: DriveLiveDie_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./frontend:/app
    networks:
      - dld-network

volumes:
  DriveLiveDie_Data:
networks:
  dld-network:
    driver: bridge
    name: dld-network
