version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: DriveLiveDie_db
    restart: no
    volumes:
      - DriveLiveDie_Data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - dld-network


  pgadming:
    image: dpage/pgadmin4
    container_name: DriveLiveDie_pgadmin
    restart: no
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - dld-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-application
    ports:
      - "8008:80"
    restart: no
    depends_on:
      - db
    networks:
      - dld-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true # This ensures that file changes are detected
    networks:
      - dld-network

volumes:
  DriveLiveDie_Data:
networks:
  dld-network:
    driver: bridge
    name: dld-network