name: backend-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -U pytest pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/backend" >> $GITHUB_ENV

      - name: Run pytest
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
        working-directory: ./backend/test
