name: backend-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -U pytest

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest backend/test --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
