name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Login to Docker Hub (or your container registry)
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: arkadiuszjuszczykue
        password: supertajnehaslo

    # Build and push Docker images
    - name: Build and Push Docker Images
      run: |
        docker-compose build
        docker-compose push

    # SSH and Deploy to VPS
    # - name: Deploy to VPS
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.VPS_HOST }}
    #     username: ${{ secrets.VPS_USERNAME }}
    #     key: ${{ secrets.VPS_SSH_KEY }}
    #     script: |
    #       cd /path/to/your/project
    #       docker-compose pull
    #       docker-compose up -d
