name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker-compose build

  backend-test:
    name: Backend Test
    needs: docker-build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker-compose build

      - name: Start Docker Compose services
        run: docker-compose up -d

      - name: Wait for database to be ready
        run: until docker-compose exec db pg_isready ; do sleep 1 ; done

      - name: Run pytest in Docker
        run: docker-compose exec -T backend pytest
        working-directory: ./backend

  frontend-test:
    name: Frontend Test
    needs: backend-test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Add pnpm to PATH
        run: echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Run tests
        run: pnpm test
        working-directory: ./frontend
