name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    allow-failure: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt  
          pip install pylint

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
